### ISSUE TITLE
Can't see map on screenshot

### ISSUE THREAD

**Issue by purrowler** [robbcocco/PokemonGo-Map-forTelegram#1]
The bot sends me a screenshot with no map. 
But when i open the website while the bot is waiting the minute im able to see the map w. pokemon. [http://prntscr.com/bvua4y](http://prntscr.com/bvua4y)
I'm running debian wheezy.

**Comment by mtrang** [comment]
Same.

**Comment by reactortrip** [comment]
same, let me know if you figure it out.  Someone else had posted in here but deleted it.  Wonder if they figured it out...

edit: I think it has something to do with the host and port.  What are you using for that? what are you suppose to use for that?

**Comment by mtrang** [comment]
I deleted the post, I thought I had figured it out and was gonna post the solution. But than it broke again.

I think it has something to do with Phantom not being able to render the new google maps formatting of the developers version of PokemonMaps.

**Comment by riorao** [comment]
the problem is solved?

**Comment by robbcocco** [comment]
Can you try increasing the time.sleep [here](https://github.com/robbcocco/PokemonGo-Map-forTelegram/blob/master/bot.py#L46)?

**Comment by purrowler** [comment]
Already tried changeing it to 10 and to 20. didn't help

**Comment by robbcocco** [comment]
Ok, i updated the map, and i'm having the same problem.
I suggest you to use the master branch of the map, it has less features but it is working well as of now

**Comment by dero2k** [comment]
Hi
having the same problem 

I tried using the master branch of the map. but with master all i get back is an empty gmap 
do you have an example on how to set it up ?

thanks

**Comment by purrowler** [comment]
Using the master branch really works. Ty!

> I tried using the master branch of the map. but with master all i get back is an empty gmap 
> do you have an example on how to set it up ?

After downloading the master branch of the map open "bot.py" with any editor and change
`os.system('python PokemonGo-Map-develop/runserver.py -a ptc -u %s -p %s -l "%s" -st %s -H %s -P %s >mapstd.txt 2>maperr.txt &' % (USER, PASS, location, STEP, HOST, PORT))`
to
`os.system('python PokemonGo-Map-master/example.py -a ptc -u %s -p %s -l "%s" -st %s -H %s -P %s >mapstd.txt 2>maperr.txt &' % (USER, PASS, location, STEP, HOST, PORT))`

after that copy "credentials.json" from the maps folder to the bots folder otherwise the map cant find it(at least for me). Open "credentials.json" with any editor and change the gmaps_key to [your own key](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key).

**Comment by reactortrip** [comment]
Still have this issue, what are y'all using for host and port?  Is it just localhost 5000?  I'm running on a Debian 7 server.

**Comment by purrowler** [comment]
> Still have this issue, what are y'all using for host and port? Is it just localhost 5000? I'm running on a Debian 7 server.

I used the domain of my server and the port 8083 since localhost didnt work & 5000 is used by something else. 
If this doesent help check mapstd.txt and maperr.txt in the bots folder for errors
