### ISSUE TITLE
Error after following steps to install and run the bot

### ISSUE THREAD

**Issue by samadsajanlal** [robbcocco/PokemonGo-Map-forTelegram#2]
Telegram bot seems to work fine except its not returning any maps. Thoughts?

**Comment by t2ac32** [comment]
i have exactly the same problem everything seem to run fine but the map are returned with a white image.

**Comment by purrowler** [comment]
check "mapstd.txt" and "maperr.txt" for errors

**Comment by samadsajanlal** [comment]
well the error I had in mapserr.txt was:

Traceback (most recent call last):
  File "PokemonGo-Map-master/example.py", line 41, in <module>
    with open('credentials.json') as file:
IOError: [Errno 2] No such file or directory: 'credentials.json'


I fixed this by putting ./ before bot.py. but now i get a blank image like t2ac32 does. no additional errors in that file or in mapstd.txt

**Comment by purrowler** [comment]
> IOError: [Errno 2] No such file or directory: 'credentials.json'

Copy "credentials.json" from the maps folder to the bots folder otherwise the map cant find it. 
Open "credentials.json" with any editor and change the gmaps_key to [your own key](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key).

**Comment by samadsajanlal** [comment]
well yeah the gmaps key is already my own. i just copied the file, though I didn't really need to (because ./bot.py vs bot.py alone fixes the problem).

Still a blank image. I saw the closed issue, but it appears that fix is already in the zip I downloaded.

**Comment by samadsajanlal** [comment]
I got it working. Steps taken:

1) Copy credentials.json to bot directory
2) Change hostname to actual hostname (not localhost)
3) Change port to anything not in use, and don't use 80 (I was always using 80)

I may submit a pull request in the near future to add these helpful tips to the readme, as these are required but missing.

**Comment by purrowler** [comment]
> 2) Change hostname to actual hostname (not localhost)
> 3) Change port to anything not in use, and don't use 80 (I was always using 80)

Yeah localhost:5000 didn't work for me too. Already said that in the closed issue.

**Comment by t2ac32** [comment]
Ok so far i changed localhost to actual localhost, copied credential.json to bot directory, im using port 202.

maperr.txt returns this 

```
Traceback (most recent call last):
  File "PokemonGo-Map-master/example.py", line 4, in <module>
    import flask
ImportError: No module named flask

```

mapstd.txt: is empty 

still receiving withe image....

**Comment by samadsajanlal** [comment]
changed localhost to actual localhost

not sure what you mean by this. do you mean you used the IP address of the server or actual hostname of the server?

also did you install the dependencies?

**Comment by t2ac32** [comment]
sorry.. i meant i used the ip adress
i ran pip install for flask and flask_googlemaps

now maperr.txt shows this.... 
`Traceback (most recent call last):
  File "PokemonGo-Map-master/example.py", line 14, in <module>
    import requests
ImportError: No module named requests
`

**Comment by purrowler** [comment]
> sorry.. i meant i used the ip adress
> i ran pip install for flask and flask_googlemaps
> 
> now maperr.txt shows this.... 
> Traceback (most recent call last): File "PokemonGo-Map-master/example.py", line 14, in <module> import requests ImportError: No module named requests 

go into the maps folder and run
`pip2.7 install --upgrade -r requirements.txt`
